package com.example.nfccardreader;
import android.app.*;import android.os.*;import android.nfc.*;import android.view.*;import android.widget.*;import android.content.*;import java.nio.charset.Charset;import java.text.SimpleDateFormat;import java.util.*;import org.json.*;
public class MainActivity extends Activity implements NfcAdapter.ReaderCallback{
 NfcAdapter nfc; TextView status,details; LinearLayout history; SharedPreferences p; SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.getDefault());
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("cards",0);nfc=NfcAdapter.getDefaultAdapter(this); LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,24,24,24);
 TextView title=new TextView(this);title.setText("📡 NFC Card Reader");title.setTextSize(25);title.setTypeface(null,1);r.addView(title);status=new TextView(this);status.setTextSize(18);status.setPadding(0,20,0,15);r.addView(status);
 Button scan=new Button(this);scan.setText("Approchez une carte NFC");scan.setOnClickListener(v->{if(nfc==null)toast("NFC non disponible");else if(!nfc.isEnabled())toast("Activez le NFC dans les paramètres");else status.setText("📲 Approchez la carte du téléphone…");});r.addView(scan);
 details=new TextView(this);details.setTextSize(16);r.addView(details);TextView h=new TextView(this);h.setText("Cartes enregistrées");h.setTextSize(21);h.setTypeface(null,1);r.addView(h);ScrollView s=new ScrollView(this);history=new LinearLayout(this);history.setOrientation(LinearLayout.VERTICAL);s.addView(history);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button clear=new Button(this);clear.setText("Effacer l'historique");clear.setOnClickListener(v->{p.edit().remove("data").apply();refresh();});r.addView(clear);setContentView(r);refresh();setStatus();}
 void setStatus(){if(nfc==null)status.setText("⚠ NFC non disponible");else if(!nfc.isEnabled())status.setText("⚠ NFC désactivé");else status.setText("📡 NFC prêt — approchez une carte");}
 protected void onResume(){super.onResume();if(nfc!=null&&nfc.isEnabled()){int flags=NfcAdapter.FLAG_READER_NFC_A|NfcAdapter.FLAG_READER_NFC_B|NfcAdapter.FLAG_READER_NFC_F|NfcAdapter.FLAG_READER_NFC_V; nfc.enableReaderMode(this,this,flags,null);}}
 protected void onPause(){if(nfc!=null)try{nfc.disableReaderMode(this);}catch(Exception e){}super.onPause();}
 public void onTagDiscovered(Tag t){runOnUiThread(()->read(t));}
 void read(Tag t){String uid=hex(t.getId()),tech=Arrays.toString(t.getTechList());String rec=readNdef(t);details.setText("UID : "+uid+"\n\nTechnologies :\n"+tech+"\n\nDonnées NDEF :\n"+rec);status.setText("✅ CARTE NFC DÉTECTÉE");save(uid,tech,rec);toast("Carte NFC détectée !");}
 String readNdef(Tag t){Ndef n=Ndef.get(t);if(n==null)return "Cette carte ne contient pas de NDEF lisible.";try{n.connect();NdefMessage m=n.getNdefMessage();if(m==null){n.close();return "Aucun message NDEF.";}StringBuilder s=new StringBuilder();for(NdefRecord r:m.getRecords())s.append(parse(r)).append("\n");n.close();return s.toString();}catch(Exception e){try{n.close();}catch(Exception z){}return "NDEF détecté mais lecture impossible : "+e.getMessage();}}
 String parse(NdefRecord r){try{byte[] type=r.getType(),d=r.getPayload();if(r.getTnf()==NdefRecord.TNF_WELL_KNOWN&&Arrays.equals(type,NdefRecord.RTD_TEXT)&&d.length>1){int l=d[0]&63;return "📝 Texte : "+new String(d,1+l,d.length-1-l,Charset.forName((d[0]&128)==0?"UTF-8":"UTF-16"));}if(r.getTnf()==NdefRecord.TNF_WELL_KNOWN&&Arrays.equals(type,NdefRecord.RTD_URI)){return "🔗 URL : "+new String(d,Charset.forName("UTF-8"));}return "Type : "+hex(type)+"\nPayload : "+hex(d);}catch(Exception e){return "Enregistrement illisible";}}
 void save(String uid,String tech,String rec){try{JSONArray a=new JSONArray(p.getString("data","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(uid.equals(o.optString("uid"))){o.put("tech",tech);o.put("records",rec);o.put("date",df.format(new Date()));p.edit().putString("data",a.toString()).apply();refresh();return;}}JSONObject o=new JSONObject();o.put("uid",uid);o.put("tech",tech);o.put("records",rec);o.put("date",df.format(new Date()));o.put("name","");a.put(o);p.edit().putString("data",a.toString()).apply();refresh();}catch(Exception e){toast("Impossible d'enregistrer");}}
 void refresh(){history.removeAllViews();try{JSONArray a=new JSONArray(p.getString("data","[]"));for(int i=a.length()-1;i>=0;i--){JSONObject o=a.getJSONObject(i);LinearLayout row=new LinearLayout(this);TextView t=new TextView(this);String name=o.optString("name","").trim();t.setText((name.isEmpty()?"Carte NFC":name)+"\n"+o.optString("uid")+" • "+o.optString("date"));t.setTextSize(15);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button v=new Button(this);v.setText("Voir");int k=i;v.setOnClickListener(x->show(k));row.addView(v);Button n=new Button(this);n.setText("Renommer");n.setOnClickListener(x->rename(k));row.addView(n);history.addView(row);}}catch(Exception e){}}
 void show(int i){try{JSONObject o=new JSONArray(p.getString("data","[]")).getJSONObject(i);new AlertDialog.Builder(this).setTitle(o.optString("name","Carte NFC")).setMessage("UID : "+o.optString("uid")+"\n\nDate : "+o.optString("date")+"\n\nTechnologies :\n"+o.optString("tech")+"\n\nNDEF :\n"+o.optString("records")).setPositiveButton("OK",null).show();}catch(Exception e){}}
 void rename(int i){try{JSONArray a=new JSONArray(p.getString("data","[]"));JSONObject o=a.getJSONObject(i);EditText e=new EditText(this);e.setSingleLine();e.setText(o.optString("name",""));new AlertDialog.Builder(this).setTitle("Renommer la carte").setView(e).setNegativeButton("Annuler",null).setPositiveButton("Enregistrer",(d,w)->{try{o.put("name",e.getText().toString().trim());p.edit().putString("data",a.toString()).apply();refresh();}catch(Exception z){}}).show();}catch(Exception e){}}
 static String hex(byte[] b){StringBuilder s=new StringBuilder();if(b!=null)for(byte x:b)s.append(String.format(Locale.US,"%02X",x));return s.toString();}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
